main:
  endorse: false
  footerBelowFold: true
  enableDarkMode: false
  modes: ["light"]
  breakpoint: "md"

favicon:
  logo: /images/logo.png

navigation:
  logo: ""
  search: true
  searchModal: true
  size: xl
  #color: primary
  # horizontal: true
  toc: true
  sidebar: true
  breadcrumb: false

sharing:
  enabled: false
  webshare: false

# Boğaziçi Dark Blue: "#1e4a8b"
# Boğaziçi Light Blue: "#8cc8ea"
style:
  primary: "#1e4a8b"
  fontSizeBase: "1.1rem"
  themeFont: "Open Sans"
  themeFontPath: "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400..800;1,400..800&display=swap"

banner:
  enabled: true
  partial: prospective

eventbar:
  enabled: true
  limit: 3
  layout: card

newsroom:
  enabled: true
  limit: 3
  layout: card
  image_settings:
    hero: "1400x700 webp q90 Smart"
    quality: 90

social:
  - name: "Twitter"
    icon: "twitter"
    url: "https://twitter.com/bogazici_cmpe"
    weight: 10
  - name: "GitHub"
    icon: "git"
    url: "https://github.com/bouncmpe"
    weight: 20
  - name: "YouTube"
    icon: "youtube"
    url: "https://www.youtube.com/@baboruncmpe"
    weight: 30

contact:
  address:
    en: "Department of Computer Engineering, Boğaziçi University, 34342 Bebek, Istanbul, Turkey"
    tr: "Bilgisayar Mühendisliği Bölümü, Boğaziçi Üniversitesi, 34342 Bebek, İstanbul, Türkiye"
  phone: "+90 212 359 45 23/24"
  fax: "+90 212 2872461"

mermaid:
  align: center

github:
  repo: "https://github.com/bouncmpe/bouncmpe.github.io"
  branch: "main"
# sections:
#   about:
#     title:
#     layout: card
#     sort: weight
#     style: rounded-1 px-4 pb-3 my-0
#     header: none
#     footer: none
#     padding: 2
#     cols: 3
#     orientation: stacked
#     fullCover: true
#     reverse: false
#     nested: false
#   g:
#     layout: card
#     header: none
#     footer: none
#     cols: 4
#     padding: 0
#   u:
#     layout: card
#     header: none
#     footer: none
#     cols: 4
#     padding: 0
#   prospective:
#     layout: card
#     sort: weight
#     style: rounded-0 px-4 pb-3 my-0
#     header: none
#     footer: none
#     padding: 2
#     cols: 3
#     orientation: stacked
#     fullCover: true
#     reverse: false
#     nested: false
#   people:
#     layout: card
#     sort: weight
#     style: border-0 px-4 pb-3 my-0 card-zoom
#     header: none
#     footer: none
#     padding: 2
#     cols: 2
#     orientation: stacked
#     fullCover: true
#     reverse: false
#     nested: false
#   courses:
#     sort: weight
#     style: rounded-1 card-zoom
#     header: none
#     footer: none
#     padding: 3
#     cols: 4
#     orientation: stacked
#     color: body-tertiary
#     reverse: false
#     nested: false
#     fullCover: true
#   undergraduate:
#     sort: weight
#     style: rounded-1 card-zoom
#     header: none
#     footer: none
#     padding: 3
#     cols: 4
#     orientation: stacked
#     color: body-tertiary
#     reverse: false
#     nested: false
#   graduate:
#     sort: weight
#     style: rounded-1 card-zoom
#     header: none
#     footer: none
#     padding: 3
#     cols: 3
#     orientation: stacked
#     color: body-tertiary
#     reverse: false
#     nested: false
#   research:
#     layout: card
#     sort: weight
#     style: rounded-1 card-zoom
#     header: none
#     footer: none
#     padding: 3
#     cols: 4
#     orientation: stacked
#     color: body-tertiary
#     reverse: false
#     nested: false
#   docs:
#     layout: card
