main:
  endorse: false
  footerBelowFold: true
  enableDarkMode: false
  modes: ["light"]
  breakpoint: "md"

favicon:
  logo: /images/logo.png

navigation:
  logo: ""
  search: true
  searchModal: true
  size: xl
  #color: primary
  # horizontal: true
  toc: true
  sidebar: true
  breadcrumb: false

sharing:
  enabled: false
  webshare: false

# Boğaziçi Dark Blue: "#1e4a8b"
# Boğaziçi Light Blue: "#8cc8ea"

style:
  primary: "#1e4a8b"
  fontSizeBase: "1.1rem"
  themeFont: "Open Sans"
  themeFontPath: "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400..800;1,400..800&display=swap"

banner:
  enabled: true
  partial: prospective

eventbar:
  enabled: true
  limit: 3
  layout: card

newsroom:
  enabled: true
  limit: 3
  layout: card
  image_settings:
    hero: "1400x700 webp q90 Smart"
    quality: 90

social:
  - name: "Twitter"
    icon: "twitter"
    url: "https://twitter.com/bogazici_cmpe"
    weight: 30
  - name: "GitHub"
    icon: "git"
    url: "https://github.com/bouncmpe"
    weight: 20

mermaid:
  align: center

github:
  repo: "https://github.com/bouncmpe/bouncmpe.github.io"
  branch: "main"
